=== DotskinMaksim/trips-data-repo/reisid.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="reisid">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="reis">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sihtkoha_linn" type="xs:string" />
							<xs:element name="hind" type="xs:string" />
							<xs:element name="inimeste_arv" type="xs:unsignedByte" />
							<xs:element name="kuupaev" type="xs:date" />
							<xs:element name="lennureis_kaasas" type="xs:unsignedByte" />
							<xs:element name="hotell">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="hotelli_aadress" type="xs:string" />
										<xs:element name="toitumine_kaasas" type="xs:unsignedByte" />
										<xs:element name="hotelli_tarnide" type="xs:unsignedByte" />
										<xs:element name="oode_arv" type="xs:unsignedByte" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="sihtkoha_linn" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DotskinMaksim/trips-data-repo/reisid.xml
<?xml version="1.0" encoding="utf-8" ?>

<reisid xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reisid.xsd">
	<reis sihtkoha_linn="Jiangchang">
		<sihtkoha_linn>Jiangchang</sihtkoha_linn>
		<hind>€974,76</hind>
		<inimeste_arv>4</inimeste_arv>
		<kuupaev>2023-11-05</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>42 Kennedy Pass</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>5</hotelli_tarnide>
			<oode_arv>12</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Hanamaki">
		<sihtkoha_linn>Hanamaki</sihtkoha_linn>
		<hind>€720,32</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2024-08-07</kuupaev>
		<lennureis_kaasas>0</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>33709 Stuart Park</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>5</hotelli_tarnide>
			<oode_arv>14</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Tobilolong">
		<sihtkoha_linn>Tobilolong</sihtkoha_linn>
		<hind>€521,70</hind>
		<inimeste_arv>9</inimeste_arv>
		<kuupaev>2024-02-08</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>23678 Trailsway Street</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>5</hotelli_tarnide>
			<oode_arv>14</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Vejprnice">
		<sihtkoha_linn>Vejprnice</sihtkoha_linn>
		<hind>€871,73</hind>
		<inimeste_arv>4</inimeste_arv>
		<kuupaev>2023-11-27</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>958 Evergreen Street</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>3</hotelli_tarnide>
			<oode_arv>17</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Višnové">
		<sihtkoha_linn>Višnové</sihtkoha_linn>
		<hind>€160,78</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2024-04-24</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>305 Springview Crossing</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>4</hotelli_tarnide>
			<oode_arv>14</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Gjøvik">
		<sihtkoha_linn>Gjøvik</sihtkoha_linn>
		<hind>€750,39</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2023-12-30</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>43309 Bunting Avenue</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>4</hotelli_tarnide>
			<oode_arv>6</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Karpokhórion">
		<sihtkoha_linn>Karpokhórion</sihtkoha_linn>
		<hind>€987,79</hind>
		<inimeste_arv>7</inimeste_arv>
		<kuupaev>2024-07-28</kuupaev>
		<lennureis_kaasas>0</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>10 Atwood Parkway</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>3</hotelli_tarnide>
			<oode_arv>9</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Lykóvrysi">
		<sihtkoha_linn>Lykóvrysi</sihtkoha_linn>
		<hind>€751,43</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2024-07-04</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>696 Ridge Oak Pass</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>3</hotelli_tarnide>
			<oode_arv>10</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Dongchong">
		<sihtkoha_linn>Dongchong</sihtkoha_linn>
		<hind>€900,56</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2023-11-09</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>41 Debra Crossing</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>4</hotelli_tarnide>
			<oode_arv>16</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Bandung">
		<sihtkoha_linn>Bandung</sihtkoha_linn>
		<hind>€314,64</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2024-05-12</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>42769 Cordelia Lane</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>1</hotelli_tarnide>
			<oode_arv>10</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Hetang">
		<sihtkoha_linn>Hetang</sihtkoha_linn>
		<hind>€310,83</hind>
		<inimeste_arv>6</inimeste_arv>
		<kuupaev>2024-06-12</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>4040 Mosinee Place</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>1</hotelli_tarnide>
			<oode_arv>8</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Farsta">
		<sihtkoha_linn>Farsta</sihtkoha_linn>
		<hind>€865,95</hind>
		<inimeste_arv>6</inimeste_arv>
		<kuupaev>2024-08-05</kuupaev>
		<lennureis_kaasas>0</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>7002 Oakridge Crossing</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>2</hotelli_tarnide>
			<oode_arv>7</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Wadi">
		<sihtkoha_linn>Wadi</sihtkoha_linn>
		<hind>€458,27</hind>
		<inimeste_arv>2</inimeste_arv>
		<kuupaev>2024-07-14</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>75 Melvin Drive</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>3</hotelli_tarnide>
			<oode_arv>4</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Hägersten">
		<sihtkoha_linn>Hägersten</sihtkoha_linn>
		<hind>€470,17</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2023-11-02</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>2 Heffernan Terrace</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>2</hotelli_tarnide>
			<oode_arv>16</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Skaramangás">
		<sihtkoha_linn>Skaramangás</sihtkoha_linn>
		<hind>€500,00</hind>
		<inimeste_arv>8</inimeste_arv>
		<kuupaev>2024-09-02</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>9 Stone Corner Center</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>5</hotelli_tarnide>
			<oode_arv>12</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Iznoski">
		<sihtkoha_linn>Iznoski</sihtkoha_linn>
		<hind>€231,96</hind>
		<inimeste_arv>5</inimeste_arv>
		<kuupaev>2023-09-14</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>49 Sycamore Center</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>2</hotelli_tarnide>
			<oode_arv>5</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Shalqiya">
		<sihtkoha_linn>Shalqiya</sihtkoha_linn>
		<hind>€237,17</hind>
		<inimeste_arv>9</inimeste_arv>
		<kuupaev>2023-12-11</kuupaev>
		<lennureis_kaasas>0</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>789 Towne Court</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>2</hotelli_tarnide>
			<oode_arv>18</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Täby">
		<sihtkoha_linn>Täby</sihtkoha_linn>
		<hind>€530,11</hind>
		<inimeste_arv>7</inimeste_arv>
		<kuupaev>2024-02-04</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>2306 Carey Way</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>2</hotelli_tarnide>
			<oode_arv>20</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Balogo">
		<sihtkoha_linn>Balogo</sihtkoha_linn>
		<hind>€604,41</hind>
		<inimeste_arv>3</inimeste_arv>
		<kuupaev>2023-12-31</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>9 Melody Circle</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>4</hotelli_tarnide>
			<oode_arv>1</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Youlan">
		<sihtkoha_linn>Youlan</sihtkoha_linn>
		<hind>€822,13</hind>
		<inimeste_arv>6</inimeste_arv>
		<kuupaev>2024-06-15</kuupaev>
		<lennureis_kaasas>0</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>8649 Vidon Terrace</hotelli_aadress>
			<toitumine_kaasas>0</toitumine_kaasas>
			<hotelli_tarnide>5</hotelli_tarnide>
			<oode_arv>18</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Liverpool">
		<sihtkoha_linn>Liverpool</sihtkoha_linn>
		<hind>€104,04</hind>
		<inimeste_arv>7</inimeste_arv>
		<kuupaev>2024-02-16</kuupaev>
		<lennureis_kaasas>0</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>97256 Norway Maple Plaza</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>1</hotelli_tarnide>
			<oode_arv>3</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Bzou">
		<sihtkoha_linn>Bzou</sihtkoha_linn>
		<hind>€962,78</hind>
		<inimeste_arv>1</inimeste_arv>
		<kuupaev>2024-02-14</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>48256 Michigan Pass</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>3</hotelli_tarnide>
			<oode_arv>19</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Jinshan">
		<sihtkoha_linn>Jinshan</sihtkoha_linn>
		<hind>€130,92</hind>
		<inimeste_arv>2</inimeste_arv>
		<kuupaev>2024-01-28</kuupaev>
		<lennureis_kaasas>1</lennureis_kaasas>

		<hotell>
			<hotelli_aadress>8546 Mcguire Junction</hotelli_aadress>
			<toitumine_kaasas>1</toitumine_kaasas>
			<hotelli_tarnide>1</hotelli_tarnide>
			<oode_arv>17</oode_arv>
		</hotell>
	</reis>
	<reis sihtkoha_linn="Tongkiling">
		<sihtkoha_linn>Tongkiling</sihtkoha_linn>
		<hind>€209,71</hind>
		<inimeste_arv>3</inimeste_arv>
		<kuupaev>2024-02-09</kuupaev>
		<lennureis_kaasas>0</lennureis_kaasas>

		<hotell>
